pcdshub/superscore

.github/PULL_REQUEST_TEMPLATE.md, conda-recipe/meta.yaml, dev-requirements.txt, docs/pre-release-notes.sh, docs/release_notes.py, docs/source/upcoming_changes.rst, docs/source/upcoming_release_notes/2-enh_main_window.rst, docs/source/upcoming_release_notes/template-full.rst, docs/source/upcoming_release_notes/template-short.rst, pyproject.toml, requirements.txt, superscore/__main__.py, superscore/bin/main.py, superscore/bin/ui.py, superscore/tests/test_blank.py, superscore/tests/test_window.py, superscore/ui/main_window.ui, superscore/utils.py, superscore/widgets/core.py, superscore/widgets/window.py
* adds blank main window, along with DesignerDisplay subclass from pcdsutils
* Adds `superscore ui` cli entrypoiint, albeit without any arguments
* Adds a real test for some ✅ 
* updates dependencies for tests and docs
* add pre-release note framework
Starting off this repo with some skeleton content
Unit test added
This PR
=> ENH/MNT: Add main window, real test

conda-recipe/meta.yaml, docs/source/upcoming_release_notes/5-add_dataclass_skeletons.rst, requirements.txt, superscore/model.py, superscore/tests/test_model.py, superscore/type_hints.py, superscore/utils.py
Add skeleton dataclasses (Parameter, Value, Collection, Snapshot, Setpoint, Readback), client, and backend.  Functions are defined and some default parameters given, but no implementations are supplied.
Supply interfaces so that we can begin parallel work on implementations.  Although the interfaces can change while we develop, having a rough known starting point should help if we work on separate components.
Tested by running `pytest` from within the repo.
Further tests may be forthcoming as I review the tests from #4.
These interfaces are adapted from the following screenshot of our block diagrams.
=> Add skeleton dataclasses, client, and backend

docs/source/upcoming_release_notes/24-enh_client_backend.rst, superscore/backends/core.py, superscore/client.py
Skeleton structure for Client and Backend. 
To-Do:
- figure out if we can add any reasonable tests at this point
- think about whether a "root" node is reasonable / necessary
- My pitch for this is that we need a way to get the top-level `Entry`'s, to populate an initial preview of the database (tree view).  As it stands there's no way to distinguish a "parent" from a "child".
- A simple way of doing this might be to just have a simple `Root` container that holds the top-level `Entry`'s.  This could have a static UUID so we can always grab it.
- add exceptions module?
We want to broadly agree on the available methods so we can do other work.
closes #23
closes #13 
Adding some tests, we need to add more
This PR, design doc
=> ENH: initial skeleton for Client and Backend

docs/source/upcoming_release_notes/27-Add_testing_backend_and_linac_fixture.rst, superscore/backends/core.py, superscore/backends/test.py, superscore/errors.py, superscore/tests/conftest.py, superscore/tests/test_backend.py
Add `TestBackend`: stores `Entry`s in-memory for easy modification and fast access.  Direct object manipulation avoids the need to implement `update_entry` or `add_entry` at this time.
Add `linac_backend` test fixture: provides a large-ish tree of `Collection`s and `Parameter`s for tests where a larger tree is needed, such as recursive functions.  Can be modified within a test to provide different test conditions. Roughly follows the AD LINAC structure for ease of navigation.
Edit `_Backend.delete_entry` docstring to specify that the method raises an error when the `Entry` passed in as an argument is out-of-sync with the backend.  Being out-of-sync means that an `Entry` with a matching UUID exists in the backend, but its data is different. Closes #30 
Introduce custom exceptions: …
=> Add initial test infrastructure: testing backend and general-use test fixture

docs/source/upcoming_release_notes/28-entry_validation.rst, superscore/backends/test.py, superscore/model.py, superscore/tests/conftest.py, superscore/tests/test_model.py
* Add `.validate()` method for all `Entry` subclasses
* Introduce `Nestable` interface for `Collection` and `Snapshot`
Validation ensures that `Entry`s are well formed before certain uses, such as inserting into a backend: close #11 
Adding validation methods to each `Entry` subclass leverages polymorphism to keep validation code close to the data being validated.  This also keeps the client or backend agnostic to the type of `Entry` being validated.
`Entry.validate()` uses an `apischema` serialization roundtrip to perform type checks. This implementation captures `ValidationError`s and returns `False` if type checks fail, but I'd be open to leaving the exception if that's preferred.  If a subclass needs specific validation tests, it can override this method; the subclass is responsible …
=> Add Entry validation methods

conda-recipe/meta.yaml, dev-requirements.txt, docs/source/upcoming_release_notes/35-enh_control_layer.rst, pyproject.toml, requirements.txt, superscore/control_layers/__init__.py, superscore/control_layers/_aioca.py, superscore/control_layers/_base_shim.py, superscore/control_layers/core.py, superscore/control_layers/core.pyi, superscore/control_layers/status.py, superscore/errors.py, superscore/tests/conftest.py, superscore/tests/test_cl.py, superscore/tests/test_status.py
- adds Shim layers, for unifying interface between different EPICS communication libraries
- adds ControlLayer, which dispatches to the appropriate shim layer.  The intent is for the client to hold onto a `ControlLayer` and send requests to the control system through it.
<details><summary>Async thoughts</summary>
<p>
We have the opportunity here to be more async about this from the start.  Since we're doing a lot of effectively IO-bound tasks (sending signal to EPICS and waiting for a response), async was a good fit.  However, I did not want to expose the async interface to the user.  I think it makes sense to stop the async-ing at the ControlLayer, so that the Client (and user) won't be exposed.  This is important if we want, frankly, anybody else at SLAC to use this code. 
`asyncio` has …
=> ENH: Control layer and shim layers

docs/source/upcoming_release_notes/38-gui_main_window.rst, superscore/qt_helpers.py, superscore/tests/test_page.py, superscore/tests/test_qt_helpers.py, superscore/tests/test_widgets.py, superscore/type_hints.py, superscore/ui/collection_page.ui, superscore/ui/main_window.ui, superscore/ui/name_desc_tags_widget.ui, superscore/ui/tags_elem.ui, superscore/widgets/core.py, superscore/widgets/manip_helpers.py, superscore/widgets/page/collection.py, superscore/widgets/page/entry.py, superscore/widgets/tree.py, superscore/widgets/window.py
- Adds `DataWidget` and `NameDescTagsWidget`, components for making widgets that communicate with dataclasses
- Adds `EntryItem` and `RootTree` for representing Entry dataclasses in a tree view
- Adds one sample Collection widget to demonstrate how to use these widget mixins
To-Do, possibly in followup issues:
- Make a QDataclassBridge type for a set specifically, to support tag addition
- Rework Tags entry when we figure out where we're storing tags
We need a framework to make a GUI.
I lifted most of this from ATEF, and as such we should be free to challenge any of the things we've built here.  We've found it quite useful, and I think it can be similarly useful here.  There should definitely be a keen eye taken to these.  While we've proven they work, they shouldn't be taken as gospel. …
=> GUI: Basic GUI elements, DataWidget pages

docs/source/upcoming_release_notes/53-enh_client_apply.rst, superscore/client.py, superscore/control_layers/__init__.py, superscore/control_layers/core.py, superscore/control_layers/status.py, superscore/tests/conftest.py, superscore/tests/test_cl.py, superscore/tests/test_client.py, superscore/tests/test_status.py
- Adds Client.apply method, for writing values to the control system
- Adjusts use of `TaskStatus` to actually capture exceptions, instead of propagating them
closes #7 
Assorted thoughts
- In the future it may be worth validating these Entries before applying them
- `TaskStatus` was built to hold exceptions raised in the coroutines they wrap, but were propagating them to the calling context.  This was caused by our used of `asyncio.gather`, which needed the `return_exceptions=True` kwarg.  `asyncio` has various ways of handling and propagating exceptions, we just needed to choose the right one for us.
Basic unit test added
This PR, docstrings etc
=> ENH: add Client.apply method, adjust TaskStatus to properly capture exceptions

docs/source/upcoming_release_notes/54-enh_config_client.rst, superscore/backends/__init__.py, superscore/backends/test.py, superscore/client.py, superscore/control_layers/core.py, superscore/tests/config.cfg, superscore/tests/test_client.py
- Adds ability for `Client` to search for configuration files, and load settings from them.
- Searches, in order:
- `$SUPERSCORE_CFG` environment variable
- `$XDG_CONFIG_HOME` directory, for files named `superscore.cfg` or `.superscore.cfg`
- `~/.config` directory, for files named `superscore.cfg` or `.superscore.cfg`
closes #8 
Added a couple tests.  Otherwise interactive tests
This PR
=> ENH: Add ability to instantiate Client from configuration file

docs/source/upcoming_release_notes/63-bug_fs_newline.rst, superscore/backends/filestore.py
Add a blank newline whenever writing the filestore .json file
Stumbled into this.  The json would fail pre-commit checks every time we tried to commit it.   While infrequent this is something that's easily avoided.
Without this, we would fail pre-commit
Interactively
This PR
=> BUG: add a newline at end of filestore json file

conda-recipe/meta.yaml, docs/source/upcoming_release_notes/56-gui_search_page.rst, requirements.txt, superscore/backends/filestore.py, superscore/client.py, superscore/tests/test_backend.py, superscore/tests/test_page.py, superscore/ui/main_window.ui, superscore/ui/search_page.ui, superscore/widgets/page/search.py
- adds a first pass at a search page
- adjusts backend search method to accept search terms that aren't simply key-value matches.  Including:
- Entry type match
- date range (start, end date)
TO-DO (in later PRs)
Moving toward #45 
interactively
This PR
=> GUI / ENH: Add search page, augment search terms

conda-recipe/meta.yaml, docs/source/upcoming_release_notes/64-gui_open_page.rst, requirements.txt, superscore/tests/test_window.py, superscore/ui/search_page.ui, superscore/widgets/page/__init__.py, superscore/widgets/page/search.py, superscore/widgets/window.py
- Adds an open-page slot that can be passed to other pages
- Passes this to the search page for opening search results
- Adds some icons for fun, adds them to tabs
- Sets up `superscore ui` to open the search page automatically, which now requires a `SUPERSCORE_CFG` to be discoverable
closes #62 
Interactively
This PR
=> GUI: Open page method, add some icons

docs/source/upcoming_release_notes/69-gui_top_tree.rst, superscore/backends/core.py, superscore/tests/conftest.py, superscore/tests/test_page.py, superscore/tests/test_window.py, superscore/widgets/__init__.py, superscore/widgets/page/__init__.py, superscore/widgets/page/search.py, superscore/widgets/tree.py, superscore/widgets/window.py
- Adds top-level tree to main window
- Adds icons to the TreeModel
- Adds fill_uuid method to TreeModel, which grabs data from client if possible
- Adds context menu on tree view for accessing custom actions.  Currently only has an open-page action, but later could include more
- Adds a couple tests
closes #44 
Interactively.  Am I getting lazy with gui tests?  Do I just fear them?  Is it a superposition? 🤔 
I added a couple tests, gui testing can be finicky
This PR.
=> GUI: add top level tree to main window

docs/source/upcoming_release_notes/57-snapshot_saving.rst, superscore/client.py, superscore/control_layers/core.py, superscore/tests/conftest.py, superscore/tests/test_client.py, superscore/tests/test_model.py
* Implement `Snapshot` saving (closes #32 )
* include helper methods `Client._build_snapshot` and `Client._gather_pvs`
* Extend `Client._gather_data` to accept any type of `Entry`, and make iterative rather than recursive
`Client.snap` itself is simple: it gathers all of the PVs in an entry, adds in the meta PVs, asynchronously fetches data for each PV, and then builds the snapshot. This method is named `snap` because `save` is currently used for the method that writes entries to the backend.
Since we want a function to gather all of the PVs from an entry, I decided to avoid code duplication by adding that functionality to `Client._gather_data`.  This extension needed some messy code to handle all of the parameter permutations, which I was able to simplify by changing the method to be …
=> ENH: Implement snapshot saving

docs/source/upcoming_release_notes/73-enh_unify_data.rst, superscore/client.py, superscore/control_layers/__init__.py, superscore/control_layers/_aioca.py, superscore/control_layers/_base_shim.py, superscore/control_layers/core.py, superscore/model.py, superscore/tests/db/filestore.json, superscore/tests/test_client.py
Standardize our data handling to create and expect EpicsData instead of backend-specific data types.
Adjust tests and Client methods to comply with this change
We weren't handling status and severity before, and we should do so in a unified way
closes #71 
Various libraries handle this EPICS metadata differently.  
* `aioca` defines an `AugmentedValue` protocol, which in python just means it's promising the returned value will have the same fields as `AugmentedValue`.  In reality the returned values are `epicscorelibs.ca.dbr.<ca_datatype>` types, which subclass python primitives and ONLY have fields dictated by the `format` kwarg
* This means that even though the return value supposedly implements the `AugmentedValue` interface, it's not guaranteed to.  (tsk tsk)
* `pyepics` gets this …
=> ENH: Unify data handling under `EpicsData`

conda-recipe/meta.yaml, dev-requirements.txt, docs/source/upcoming_release_notes/34-ioc_infrastructure.rst, superscore/control_layers/core.py, superscore/tests/conftest.py, superscore/tests/ioc/__init__.py, superscore/tests/ioc/ioc_factory.py, superscore/tests/ioc/linac.py, superscore/tests/test_ioc.py
Add a fixture and module for instantiating IOCs that make PVs accessible via EPICS during tests and for live interaction (closes #31) 
Fix a bug where the `dummy_cl` fixture was altering the `SHIMS` global variable, causing the IOC test to fail only if run after `test_cl.py`.  I did this both by making a new dict in `dummy_cl`, and by copying `SHIMS` in `ControlLayer.__init__` rather than assigning it to an instance attribute.
This application needs to interface with EPICS via Channel Access and PV Access, so we need a way to test this interface. While mocking can be useful, using actual EPICS tools in at least some tests will make the test suite more complete. This test IOC system is intended to provide test PVs that use the same interface as and behave like production PVs, while being …
=> TST: Implement test IOC

docs/source/upcoming_release_notes/77-mnt_snap_ro_readback.rst, superscore/client.py, superscore/tests/test_client.py
If a `Parameter` in a `Collection` is marked as `read_only=True`, it should be captured as a `Readback` in the corresponding `Snapshot`.
Previously it would always be captured as a `Setpoint`, which is implicitly read-write, and did not have tolerance information
Stumbled across this in another effort
I have not yet added a test
This PR
=> MNT: read-only Parameters should be snapshotted as Readback, and propagate tolerances

docs/source/upcoming_release_notes/72-mnt_common_views.rst, superscore/control_layers/core.py, superscore/tests/test_views.py, superscore/tests/test_widgets.py, superscore/widgets/page/entry.py, superscore/widgets/page/search.py, superscore/widgets/views.py, superscore/widgets/window.py
Build a couple table models that can hopefully be reused elsewhere.  Includes:
- `LivePVTableModel`: a model for displaying {Parameter, Readback, Setpoint} data alongside the current values
- `NestableTableModel`: a model for {Collection, Snapshot} entries, which shows title / description primarily
- `BaseTableModel` that holds their own entries
Also:
- refactors a bit of the existing table models
- Adds a `_PVPollThread` for grabbing data outside the GUI thread
Note: I renamed `superscore.widgets.tree` -> `superscore.widgets.views`, but the diff viewer doesn't pick that up.  I did not change the tree model at all, so the reviews can focus on the table models
To-do (in a later PR at this point):
Building screens, I fell down this rabbit hole and the diff warranted a separate PR …
=> MNT: Common table views, Primarily LivePVTableModel, minor skeleton work on NestableTableModel

docs/source/upcoming_release_notes/78-cl_get_return_com_error.rst, superscore/control_layers/core.py, superscore/tests/test_cl.py
Adjust `_get_single` to intercept and return a `CommunicationError` rather than propagating it.
`_get_one` still raises the error so that alternative `get` methods will still propagate the error unless they make the decision to return it.
Context in #74 
New test: `test_cl.py::test_get_communication_error`
This PR
=> MNT: return error rather than raising in ControlLayer._get_single

docs/source/upcoming_release_notes/80-enh_coll_builder.rst, superscore/tests/test_page.py, superscore/ui/collection_builder_page.ui, superscore/ui/main_window.ui, superscore/widgets/enhanced.py, superscore/widgets/page/collection_builder.py, superscore/widgets/views.py, superscore/widgets/window.py
- adds CollectionBuilderPage, with fields/forms for adding Parameters, sub-Collections to a collection
- Utilizes shared `LivePVTableModel` and `NestableModel`
- Adds a `FilterableComboBox`
To-Do:
closes #49 
Interactively, tests to be added
This PR.
=> ENH: add FilterComboBox, CollectionBuilderPage

docs/source/upcoming_release_notes/79-augment_search_methods.rst, superscore/backends/core.py, superscore/backends/filestore.py, superscore/client.py, superscore/tests/test_backend.py, superscore/tests/test_client.py, superscore/widgets/page/collection_builder.py, superscore/widgets/page/search.py, superscore/widgets/views.py
* Change search term format from keyword arg to namedtuple of `(<attribute>, <operator>, <value>)`
* Define `SearchTerm` namedtuple
* Modify search page, views, and tests to use new format
Closes #61 
A three-term format provides more flexibility than a keyword arg. For example, we'd run into trouble using keyword args if we wanted to support both exact match and fuzzy match on entry titles, but with the tuple format we can apply different operators to the same attribute / value pairs.
Using a namedtuple for the format provides the option of setting and accessing args by name without taking more memory than bare tuples.  
I included the operators:
* `eq` (equals)
* `lt` (less than or equal to)
* `gt` (greater than or equal to)
* `in` (item in container)
* `like` (partial match)
* …
=> ENH: Augment search methods

docs/source/upcoming_release_notes/89-tab_widget_cleanup.rst, superscore/widgets/window.py
Fix bug where `LivePVTableModel` polling threads aren't cleaned up when the main window is closed.
Closes #88 
See #88 
Interactively
=> BUG: close tabs in tab widget when main window is closed

docs/source/upcoming_release_notes/90-enh_pv_nest_views.rst, superscore/control_layers/_aioca.py, superscore/control_layers/_base_shim.py, superscore/tests/conftest.py, superscore/tests/test_page.py, superscore/tests/test_views.py, superscore/ui/collection_builder_page.ui, superscore/widgets/page/collection_builder.py, superscore/widgets/page/search.py, superscore/widgets/views.py
- Refactors shared table models to have their own self-contained table views for ease of use and extensibility
- Add methods to make columns editable for both shared table models
- Adds ValueDelegate to provide constrained editing for columns based on their datatype and metadata
- Add more metadata fields to EpicsData (precision, enums, limits, precision)
- improve enum handling for `LivePVTableView`
Going about adding more functionality.
Interactively, ensuring existing tests run
This PR
enum ValueDelegate
double ValueDelegate (must be < 0)
=> ENH/REF: refactor shared table views

docs/source/upcoming_release_notes/96-fix_fill_child_view.rst, superscore/tests/test_views.py, superscore/widgets/views.py
Actually fill child entries if they are uuids
Originally observed as a bug where entries would not be loaded into tables when you'd expect them to.  Also modifies the parent dataclass, replacing UUIDs with an Entry.  This does not recurse.
Interactively, and some tests were added
This PR.
=> FIX: actually fill child entries in shared table views

docs/source/upcoming_release_notes/94-snapshot_restore_page.rst, superscore/bin/main.py, superscore/bin/ui.py, superscore/client.py, superscore/tests/conftest.py, superscore/tests/test_page.py, superscore/ui/restore_page.ui, superscore/widgets/page/restore.py, superscore/widgets/views.py, superscore/widgets/window.py
Add restore page template and logic
Add ability to open restore page from root tree `QTreeView`
Increase default size of the main window
Fix bug where closing a `LivePVTableModel` sometimes causes an error trying to access deleted data
This page can currently show all leaf `Entry`s in a snapshot and can compare stored values to live values.  The same page is intended to be able to compare values from two snapshots and to restore saved values, but both of those capabilities are postponed for later PRs.
The AD control system has a convention where middle clicking on a UI element shows the underlying PV and copies it to the clipboard, so I added middle-click-to-copy as a partial implementation and convenience feature.  We can fill out the PV-display-and-copy later if desired. …
=> ENH: add snapshot view / compare / restore page (only view functional)

docs/source/upcoming_release_notes/98-enh_client_compare.rst, superscore/client.py, superscore/compare.py, superscore/tests/test_client.py, superscore/tests/test_compare.py
- Adds `EntryDiff`, which tracks two `Entry`s, along with a list of `DiffItem` objects
- attempts to build reasonable reprs for the above as well (WIP)
- implements `Client.compare` using the above
closes #9 
Tests added.  
This PR, #9 
Example repr:
```
> client.compare( readback1, readback2 )
Diff: {
Readback.uuid: (ecb42cdb-b703-4562-86e1-45bd67a2ab1a->8e380e15-5489-41db-a8a7-bc47a731f099)
Readback.creation_time: (2024-05-10 16:49:34.574951+00:00->2024-05-10 16:49:34.574987+00:00)
Readback.pv_name: (MY:PREFIX:mtr1.ACCL->MY:PREFIX:mtr1.VELO)
}
```
=> ENH: add Client.compare, along with dataclass diff calculation utilities

docs/source/upcoming_release_notes/97-restore_functionality.rst, superscore/bin/demo.py, superscore/tests/conftest.py, superscore/tests/demo.cfg, superscore/tests/ioc/ioc_factory.py, superscore/tests/test_page.py, superscore/ui/restore_dialog.ui, superscore/ui/restore_page.ui, superscore/widgets/page/restore.py
* Add "restore" button to restore page
* Button opens dialog with all PVs and values in a table, plus accept button
* PVs can be removed
* Accept button writes all values in the table to the EPICS system
* Accept button also turns on live data tracking, as a way of tracking restore progress
Restoring snapshots and other sets of values are a core feature of the application.
A dialog represents an action being configured and then activated, so I've used it to coordinate the restore action for now.  Alternatives include filtering the `RestorePage` main PV table, but this could muddy the app's state in the mind of the user unless it's done well.
PVs can be removed from the restore dialog, but currently not added in.  This covers cases where a whole or partial `Snapshot` needs to be restored, …
=> ENH: add restore functionality to snapshot restore page

docs/source/upcoming_release_notes/105-bug_tree_fill.rst, superscore/backends/core.py, superscore/backends/filestore.py, superscore/backends/test.py, superscore/client.py, superscore/tests/conftest.py, superscore/tests/test_client.py, superscore/tests/test_views.py, superscore/tests/test_window.py, superscore/widgets/views.py
- Make `RootTree` tree model fill uuids when expanding items.
- Adjust `Client.fill` to allow us to specify the fill extent.
- Do some maintenance on the backend classes
- upstream `FilestoreBackend.compare` into `_Backend`
- implement `.search()` in `TestBackend`
fixes #100 
There was a lot of touching up to do here, hopefully I properly handled things.
Half way into trying to gather all the signals that fire when an item is expanded, I realized there's a pair of "fetch" methods  qt provides us to handle lazy loading of data.  These are split into:
- `QAbstractItemModel.canFetchMore() -> bool`: where we set the logic to determine if data needs to be fetched
- `QAbstractItemModel.fetchMore()`: which actually fetches the data.
This actually ended up working quite smoothly, with most of my …
=> BUG: fix tree fill behavior

docs/source/upcoming_release_notes/104-parametrize_filestore_backend_fixture.rst, superscore/bin/demo.py, superscore/tests/conftest.py, superscore/tests/demo.cfg, superscore/tests/ioc/linac.py, superscore/tests/test_backend.py, superscore/tests/test_client.py, superscore/tests/test_compare.py, superscore/tests/test_page.py, superscore/tests/test_window.py
Refactor the `filestore_backend` fixture to accept parametrized args.  Each arg can be a path to a file or an iterable of functions or function names.  Function names must be accessible from the `conftest.py` namespace.  Functions must return a `Root` or an iterable of `Entry`s. 
Closes #103 
Parametrizing `filestore_backend` enables us to choose what data to use in a test without having to define a dedicated fixture.  Parametrization also allows us to easily run the same test on multiple data sources.
Supporting function names in the `conftest.py` namespace let's us select widely used data sources defined in `conftest.py` without having to import the functions.  Supporting function literals additionally let's us define more narrowly used data sources in test files and pass those into the …
=> TST: parametrize the filestore_backend fixture

docs/source/upcoming_release_notes/108-ancestor_search_option.rst, superscore/backends/filestore.py, superscore/tests/test_backend.py, superscore/tests/test_client.py
Add support for `ancestor` `SearchTerm` to `FilestoreBackend.search`
Add `FilestoreBackend._gather_progeny` utility method 
Closes #102 
With an `Entry` in one `Nestable`, it is impossible to retrieve the corresponding `Entry` in another `Nestable` using the existing `SearchTerms`.  The attributes of the known `Entry` do not reliably correspond to attributes of the desired `Entry`, other than the `.pv_name` or `.title`, so it is necessary to be able to limit searches to `Entry`s that are nested under a known `Nestable`.
A concrete use case is comparing snapshots.  For each PV in the first snapshot, the corresponding PV must be found in the second snapshot using only the PV string.  This becomes possible using the new search term.
The current implementation uses a utility method to gather …
=> ENH: add search term for retrieving Entries that are nested under an ancestor

docs/source/upcoming_release_notes/107-mnt_upstream_tree_view.rst, superscore/backends/test.py, superscore/tests/test_views.py, superscore/tests/test_widgets.py, superscore/tests/test_window.py, superscore/ui/collection_builder_page.ui, superscore/ui/main_window.ui, superscore/ui/nestable_page.ui, superscore/widgets/page/collection_builder.py, superscore/widgets/page/entry.py, superscore/widgets/views.py, superscore/widgets/window.py
- Adds common `RootTreeView` which holds the `RootTree` model
- Upstreams standard settings and context menu support
- Fills the top-level entry whenever `RootTree` model is created, to ensure at least first level of children display
Closes #101 
Interactively, and some tests have been added
Now you can double-click-to-open and right-click inside of other pages that have Tree Views
Now all pages with tree views will open with at least the first set of children populated.  
This PR
=> MNT: move context menu functionality upstream into `RootTreeView`

docs/source/upcoming_release_notes/112-gui_diff_page.rst, superscore/compare.py, superscore/tests/test_page.py, superscore/ui/diff_page.ui, superscore/widgets/core.py, superscore/widgets/page/diff.py, superscore/widgets/views.py, superscore/widgets/window.py
- Adds a Diff Page that subclasses the existing common views to add highlighting based on the calculated Diff
- Adds a QtSingleton class that allows singletons to hold signals.
- Long story short, the normal `__new__` singleton creation method doesn't quite work.  While the singletons are created correctly, the bound `QtCore.Signal`'s lose their connections every time an instance is returned
- Devan theorizes that this has to do with `__init__` doing something to the class variable signals.  I am too tired to investigate further
This description is so minimal for the amount of time I spent spinning on this 💀 
This is likely still riddled with bugs, but I want to get eyes on it before it bloats into a small planet of a diff.  I'm happy to revisit this in follow-up PRs, but I feel like …
=> GUI: add Diff-view page

docs/source/upcoming_release_notes/114-bug_tree_fetchmore_page_open.rst, superscore/tests/test_views.py, superscore/widgets/views.py
Previously `RootTree.canFetchMore` would check the dataclass members to determine if filling was necessary.  This works within the context of a single page, but if we open the a detailed page from the tree-view the dataclass may be filled without the EntryItem getting filled.
Now that `RootTree.canFetchMore` checks both the dataclass and the `EntryItem`, this desync can be avoided
Closes #113 
Interactively
This PR, pre-release notes
=> BUG: check both dataclass and EntryItem in tree view in `canFetchMore`

docs/source/upcoming_release_notes/115-ref_window_singleton.rst, superscore/tests/conftest.py, superscore/tests/test_page.py, superscore/widgets/__init__.py, superscore/widgets/core.py, superscore/widgets/page/collection_builder.py, superscore/widgets/page/diff.py, superscore/widgets/page/entry.py, superscore/widgets/page/search.py, superscore/widgets/views.py, superscore/widgets/window.py
- Makes `Window` a `QtSingleton`, and adds an access function for use throughout superscore ui widgets
- Uses this singleton to access methods that were passed around manually in the past as optional arguments or set attributes.  In particular
- Open Page Slot: removed as an optional argument on all page widgets, only retrieved by the Window singleton.  (since this argument has no meaning outside the context of the full application)
- client: Added a backup access path via `Window` singleton, but also retained the init argument.  This permits testing of widgets individually
- These methods are gathered in a `WindowLinker` mixin class for convenience and de-duplication 
I ended up treating these two differently, and am open to differing opinions here.  Perhaps I should have left the …
=> REF: create a window singleton for access throughout superscore

docs/source/upcoming_release_notes/119-mnt_pop_bknd.rst, superscore/backends/core.py, superscore/backends/test.py, superscore/bin/__init__.py, superscore/bin/demo.py, superscore/tests/conftest.py, superscore/tests/conftest_data.py, superscore/tests/test_cli.py, superscore/tests/test_client.py, superscore/tests/test_model.py, superscore/tests/test_page.py, superscore/tests/test_views.py
Re-add `populate_backend` for use in `superscore demo` and other purposes
I broke the demo command, sorry
Interactively, and some rudimentary smoke tests have been added to cover the cli
This PR
=> MNT: re-create populate_backend for use in superscore demo

docs/source/upcoming_release_notes/125-bug_refresh_window.rst, superscore/tests/test_window.py, superscore/widgets/core.py, superscore/widgets/page/collection_builder.py, superscore/widgets/window.py
Refresh the main window tree view whenever a Collection is added through the Collection Builder Page
Closes #111 
This takes advantage of the Window singleton pattern added some time ago.  Using this prevents us from having to pass specific methods/signals through to widgets.
Interactively, a simple test has been added.
This PR
=> BUG: refresh main window tree when new collection is created

docs/source/upcoming_release_notes/128-take_snapshot_button.rst, superscore/backends/filestore.py, superscore/client.py, superscore/control_layers/_aioca.py, superscore/tests/conftest_data.py, superscore/tests/test_client.py, superscore/tests/test_window.py, superscore/ui/nestable_page.ui, superscore/widgets/core.py, superscore/widgets/page/entry.py
* fix bug where `Client._build_snapshot` calls `_Backend.get`, which doesn't exist
* fix bug where `FilestoreBackend.fill_uuids` calls `setattr` with only two args
* closes #126 
* strip `AugmentedValue` metadata when setting `EpicsData.data` in `_AoicaShim`
* this was causing a bug where returning `EpicsData.data` from a view's `.data` method caused the cells to show as empty
* add button on `nestable_page.ui` (used for showing details of `Collection`s and `Snapshot`s) that takes a new snapshot for the associated `Collection`
* closes #50 
* include dialog for setting metadata for new snapshot
Taking new snapshots is a core feature of the app.  The button is placed on the detailed nestables page so that it's available for `Collection`s and `Snapshot`s.
The dialog uses a …
=> ENH: add button to take snapshots on Collection / Snapshot detail page

docs/source/upcoming_release_notes/131-bug_open_page_menu_args.rst, superscore/widgets/page/search.py, superscore/widgets/views.py
- Fixes incorrect arguments to open_page_slot, which I missed when transitioning to use `WindowLinker`
- Also adjusts ResultFilterProxyModel to make a call to the `WindowLinker` method instead of calling `get_window ` itself.
I got embarrassed by this bug during the standup and figured I should fix it
Interactively.  I'm going to skip writing a test for this one because triggering a context menu programmatically would involve too much hard coded position wrangling.  Maybe I revisit it later...
This PR
=> BUG: fix incorrect arguments to WindowLinker.open_page_slot

.pre-commit-config.yaml, docs/source/upcoming_release_notes/4-bld_precommit_autoupdate.rst, superscore/tests/test_compare.py
Run `pre-commit autoupdate`
we recently updated our runners, which moved the default python version to 3.12.  For the test runners this doesn't matter since we make an env with a specific python version, but this broke some of the older the pre-commit check hooks (flake8)
I've been told this is more ammo for switching to ruff, but I'm lazy.
CI should pass
This PR
=> BLD: precommit autoupdate

docs/source/upcoming_release_notes/140-enh_directory_backend.rst, superscore/backends/__init__.py, superscore/backends/directory.py, superscore/backends/filestore.py, superscore/bin/demo_main.py, superscore/bin/ui_main.py, superscore/model.py, superscore/tests/conftest.py, superscore/tests/demo.cfg, superscore/tests/test_backend.py
* Implement `DirectoryBackend`, which disperses entries into multiple files within a directory
* Change demo config to use `DirectoryBackend`
* Adjust Tag type so serialization continues to work
* Introduce `_Backend.reset` to aid in testing and demos
Originally authored by @shilorigins , rebased by me.  A copy of #137 and https://github.com/slaclab/superscore/pull/2
`FilestoreBackend` has very poor performance scaling, since the same large file has to read and written whenever data changes in the backend.  It also has extra complexity from `_entry_cache`, which is a common source of bugs due to improper cache invalidation and write-through handling.  `DirectoryBackend` is a solution to both of these problems, while also satisfying the need for a convenient testing / debugging backend. …
=> ENH: add Directory backend, rebased
